name: Release on push to main

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "Pre-Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Calculate release version
        run: |
          echo "release_version=1.$(date +'%g%m%d%H%M').0-alpha" >> $GITHUB_ENV
      - name: Set version
        run: |
          sed -i "s/1.SNAPSHOT/${{ env.release_version }}/g" build.gradle.kts
      - run: |
          git tag v${{ env.release_version }}
          git push --tags
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1
      - name: Running gradle build
        uses: eskatos/gradle-command-action@v1.3.3
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        with:
          arguments: build publish --no-daemon
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#          docker issuer
      - name: Build and push Docker images (issuer)
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          file: docker/issuer.Dockerfile
          tags: waltid/issuer:latest, waltid/issuer:${{ env.release_version }}
#          docker verifier
      - name: Build and push Docker images (verifier)
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          file: docker/verifier.Dockerfile
          tags: waltid/verifier:latest, waltid/verifier:${{ env.release_version }}
#          docker wallet-backend
      - name: Build and push Docker images (wallet-backend)
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          file: waltid-wallet/Dockerfile
          tags: waltid/wallet-backend:latest, waltid/wallet-backend:${{ env.release_version }}
#          docker wallet-frontend
      - name: Build and push Docker images (wallet-backend)
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          file: waltid-apps/web-wallet/Dockerfile
          tags: waltid/wallet-frontend:latest, waltid/wallet-frontend:${{ env.release_version }}

      - name: Changelog
        uses: ardalanamini/auto-changelog@v3
        id: changelog
        with:
          github-token: ${{ github.token }}
          commit-types: |
            breaking: Breaking Changes
            feat: New Features
            fix: Bug Fixes
            revert: Reverts
            perf: Performance Improvements
            refactor: Refactors
            deps: Dependencies
            docs: Documentation Changes
            style: Code Style Changes
            build: Build System
            ci: Continuous Integration
            test: Tests
            chore: Chores
            other: Other Changes
          default-commit-type: Other Changes
          release-name: v${{ env.release_version }}
          mention-authors: true
          mention-new-contributors: true
          include-compare: true
          semver: true
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.release_version }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ steps.changelog.outputs.prerelease }}
#          issuer deployment
      - name: Prepare CD - issuer
        run: sed "s/_DEFAULT_DEPLOYMENT_/$GITHUB_SHA/g" waltid-issuer/k8s/deployment-dev.yaml > waltid-issuer/k8s/deployment_mod.yaml
      - name: Continuous deployment - issuer
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -n dev -f waltid-issuer/k8s/deployment_mod.yaml
#          verifier deployment
      - name: Prepare CD - verifier
        run: sed "s/_DEFAULT_DEPLOYMENT_/$GITHUB_SHA/g" waltid-verifier/k8s/deployment-dev.yaml > waltid-verifier/k8s/deployment_mod.yaml
      - name: Continuous deployment - verifier
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -n dev -f waltid-verifier/k8s/deployment_mod.yaml
#          wallet-backend deployment
      - name: Prepare CD - wallet
        run: sed "s/_DEFAULT_DEPLOYMENT_/$GITHUB_SHA/g" waltid-wallet/k8s/deployment-dev.yaml > waltid-wallet/k8s/deployment_mod.yaml
      - name: Continuous deployment - wallet
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -n dev -f waltid-wallet/k8s/deployment_mod.yaml